[package]
name = "update-client"
version = "0.1.0"
edition = "2021"

[dependencies]
clap = { version = "4.5.13", features = ["derive"] }
json = "0.12.4"
tungstenite = { version = "0.23.0", features = ["native-tls"] }
